apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mixtral-serving-ilab
  namespace: petloan-instructlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 500Gi
