---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: prometheus-sa
  namespace: petloan-instructlab
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-view-role
  namespace: petloan-instructlab
  labels:
    opendatahub.io/dashboard: 'true'
rules:
  - verbs:
      - get
    apiGroups:
      - serving.kserve.io
    resources:
      - inferenceservices
    resourceNames:
      - prometheus
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-view
  namespace: petloan-instructlab
  labels:
    opendatahub.io/dashboard: 'true'
subjects:
  - kind: ServiceAccount
    name: prometheus-sa
    namespace: petloan-instructlab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-view-role
