apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mixtral-pvc
  namespace: petloan-instructlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3
