apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mixtral-teacher
  namespace: petloan-instructlab
  annotations:
    serving.knative.dev/creator: system:serviceaccount:petloan-instructlab:pipeline-runner
    serving.knative.dev/lastModifier: system:serviceaccount:petloan-instructlab:pipeline-runner
spec:
  predictor:
    serviceAccountName: mixtral-sa
    model:
      modelFormat:
        name: mixtral
        version: "1"
      runtime: mixtral-runtime
      storageUri: pvc://mixtral-pvc/mixtral
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mixtral-sa
  namespace: petloan-instructlab
