apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-pull
  namespace: petloan-instructlab
spec:
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ilab-pull-secret
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
        - name: docker-config
          secret:
            secretName: ilab-pull-secret
      containers:
        - name: prometheus-pull
          image: quay.io/skopeo/stable:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Pulling Prometheus model..."
              mkdir -p /storage/prometheus
              cd /storage/prometheus
              
              # Copy from Red Hat registry using skopeo
              skopeo copy --authfile /config/.dockerconfigjson \
                docker://registry.redhat.io/rhelai1/prometheus-8x7b-v20:1.0 \
                dir:/storage/prometheus
              
              echo "Prometheus model pull complete"
              ls -la /storage/prometheus
          volumeMounts:
            - name: prometheus-storage
              mountPath: /storage
            - name: docker-config
              mountPath: /config
              readOnly: true
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "2"
