---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 8b826e65-92eb-4a66-bbbd-75c91f810d01-model-cache
  namespace: petloan-instructlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 1e779bfb-390b-490c-ac5a-550a15e01e6e-sdg
  namespace: petloan-instructlab  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3
