apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: petloan-instructlab
  labels:
    app: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      serviceAccountName: nfs-server-sa
      containers:
      - name: nfs-server
        image: quay.io/external_storage/nfs-server-provisioner:latest
        ports:
        - name: nfs
          containerPort: 2049
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        args:
          - "-provisioner=manual"
          - "-grace-period=10"
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_NAME
          value: nfs-server
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: nfs-storage
          mountPath: /export
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-server-storage
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: petloan-instructlab
  labels:
    app: nfs-server
spec:
  ports:
  - name: nfs
    port: 2049
  - name: rpcbind
    port: 111
  selector:
    app: nfs-server
