apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-4
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-manual
  nfs:
    path: /nfs-data
    server: 10.131.2.51
