apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  namespace: petloan-instructlab
  labels:
    app: nfs-server
spec:
  serviceAccountName: nfs-server-sa
  containers:
  - name: nfs-server
    image: registry.redhat.io/ubi8/ubi:latest
    command: ["/bin/bash", "-c"]
    args:
    - |
      echo "Installing NFS utilities..."
      yum update -y && yum install -y nfs-utils rpcbind

      echo "Setting up NFS share..."
      mkdir -p /nfs-data
      chmod 777 /nfs-data
      echo '/nfs-data *(rw,sync,no_root_squash,no_subtree_check,insecure)' > /etc/exports

      echo "Starting RPC services..."
      rpcbind &
      sleep 2
      
      echo "Starting NFS daemon..."
      rpc.nfsd 8 &
      sleep 2
      
      echo "Starting mount daemon..."
      rpc.mountd --no-tcp &
      sleep 2
      
      echo "Exporting filesystems..."
      /usr/sbin/exportfs -ra
      
      echo "NFS server started successfully"
      /usr/sbin/exportfs -v

      # Keep running and periodically check exports
      while true; do
        sleep 30
        if ! /usr/sbin/exportfs -v > /dev/null 2>&1; then
          echo "Re-exporting filesystems..."
          /usr/sbin/exportfs -ra
        fi
      done
    ports:
    - containerPort: 2049
      name: nfs
    - containerPort: 111
      name: rpcbind
    securityContext:
      privileged: true
    volumeMounts:
    - name: nfs-storage
      mountPath: /nfs-data
  restartPolicy: Always
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: nfs-server-storage
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: petloan-instructlab
  labels:
    app: nfs-server
spec:
  ports:
  - name: nfs
    port: 2049
  - name: rpcbind
    port: 111
  selector:
    app: nfs-server
