apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cd68f64f-428e-4a04-af38-bea15bbd1ebf-sdg
  namespace: petloan-instructlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3
  volumeMode: Filesystem
