apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: simple-nfs-test-
  namespace: petloan-instructlab
spec:
  entrypoint: simple-test
  
  volumeClaimTemplates:
  - metadata:
      name: test-data
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "nfs-manual"
      resources:
        requests:
          storage: 100Gi
  
  templates:
  - name: simple-test
    container:
      image: registry.redhat.io/rhoai/odh-ml-pipelines-runtime-generic-rhel9@sha256:6704ff9674557b2866822117f5986d497e35bd23bedb1a5507fafb394cd24e0f
      command: ["/bin/bash", "-c"]
      args:
      - |
        echo "Starting simple NFS test..."
        echo "Writing test data to NFS storage..."
        mkdir -p /data/test
        echo "Test successful at $(date)" > /data/test/success.txt
        echo "Contents of /data:"
        ls -la /data/
        echo "Test completed successfully!"
        sleep 10
      volumeMounts:
      - name: test-data
        mountPath: /data
